# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dx',
            options={'verbose_name': '多选', 'verbose_name_plural': '多选'},
        ),
        migrations.AlterModelTable(
            name='dx',
            table='dx',
        ),
    ]
