# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0002_auto_20170707_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiguiinfo',
            name='yong',
            field=models.BooleanField(max_length=64, verbose_name='是否在用'),
        ),
    ]
