# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0003_auto_20170710_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiguiinfo',
            name='yong',
            field=models.BooleanField(verbose_name='是否在用'),
        ),
    ]
