# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0005_auto_20170711_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiguiinfo',
            name='d',
            field=models.ManyToManyField(to='jigui.dx', verbose_name='多选'),
        ),
    ]
