# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, verbose_name='用户组')),
            ],
            options={
                'verbose_name': '登陆用户组',
                'verbose_name_plural': '登陆用户组',
                'db_table': 'UserGroup',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '登陆用户',
                'verbose_name_plural': '登陆用户',
                'db_table': 'UserInfo',
            },
        ),
    ]
