# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Manufacturer',
            field=models.CharField(max_length=50, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_core',
            field=models.CharField(max_length=50, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=50, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(max_length=50, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='model_name',
            field=models.CharField(max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='osversion',
            field=models.CharField(max_length=50, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='product',
            field=models.CharField(max_length=50, null=True, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(max_length=50, null=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor_id',
            field=models.CharField(max_length=50, null=True, verbose_name='供应商'),
        ),
    ]
