# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0004_host_jifang'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=50, null=True, verbose_name='用户')),
                ('host', models.CharField(max_length=50, verbose_name='主机')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('port', models.CharField(max_length=50, null=True, verbose_name='端口')),
                ('cmd', models.CharField(max_length=50, null=True, verbose_name='命令')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '历史命令',
                'verbose_name_plural': '历史命令',
                'db_table': 'history',
            },
        ),
    ]
