# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间'),
        ),
    ]
