# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0006_history_ctime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='host',
        ),
    ]
